name: Docker Image CI

on: [push, pull_request, workflow_dispatch]

jobs:

  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Build Pharo 8 Docker Pushing Image to Repo
      uses: docker/build-push-action@v2
      with:
        context: 8/
        push: true
        tags: vitormcruz/pharo:8

    - name: Build Pharo 9 Docker Pushing Image to Repo
      uses: docker/build-push-action@v2
      with:
        context: 9/
        push: true
        tags: vitormcruz/pharo:9

    - name: Build Pharo 11 Docker Pushing Image to Repo
      uses: docker/build-push-action@v2
      with:
        context: 11/
        push: true
        tags: vitormcruz/pharo:11

