name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Build Docker Pushing Image to Repo
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: 8/
        push: true
        tags: vitormcruz/pharo:8

